### ISSUE TITLE
Command line system

### ISSUE THREAD

**Issue by dzikoysk** [Panda-Programming-Language/Reposilite#10]
### Current state
Missing command line system

### Expected 
* Annotation based commands
* `/help` display all available commands

### Concept
```java
class TestCommand {

    @Command("test <arg1> <arg2>")
    void test(String arg1, String arg2) { }

}
```

**Comment by GotoFinal** [comment]
I think that annotating classes is weird here, I would suggest annotating methods, that would also allow to place multiple related commands in single packages.
Do we need optional arguments? Or this will be separate task later and we don't need it right now?

This will be only for internal use so we can change and modify this later without any issues?

**Comment by dzikoysk** [comment]
Annotating methods instead of classes is a great idea, I'll update the concept. Parameters should be autowired.

Also, I'd like to provide these commands as a part of the addon API, but it's not the priority at this moment.

**Comment by GotoFinal** [comment]
We should then keep in mind that addons should have some kind of namespaces for commands so they will not collide and replace each other, especially for such commands I think that namespace should be then required part of command. But this is something we can add later when we will be ready to expose this as API
