### ISSUE TITLE
Support HEAD requests

### ISSUE THREAD

**Issue by dzikoysk** [Panda-Programming-Language/Reposilite#73]
Maven may check resource using HEAD request before GET.

Similar issue: https://github.com/dzikoysk/NanoMaven/issues/1 (~ [NanoRepositoryRouter.java#L54](https://github.com/dzikoysk/NanoMaven/blob/c22fd6d7e9ab701a5eeb912fc3c43c36b0a74fce/src/main/java/org/panda_lang/nanomaven/server/router/NanoRepositoryRouter.java#L54))

**Comment by bmstefanski** [comment]
It's already implemented in spring core 
https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-requestmapping-head-options

`HEAD` `http://localhost:3000/api/repository/maven/releases/org/panda-lang/panda-utilities/indev-0.8.0/`
```
HTTP/1.1 200
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Sun, 23 Dec 2018 20:46:00 GMT
```

/cc @dzikoysk
